Add: files with api, exceptions, workspace, view and storage API
vitalops/datatune-client pull request #1
Opened 2024-05-03 07:55 UTC by abhijithneilabraham

2024-05-06 04:36 UTC, farizrahman4u requested changes

2024-05-06 04:36 UTC, farizrahman4u commented on datatune/api.py
> +HTTP_STATUS_FORCE_LIST = [408, 429, 500, 502, 503, 504]
Move these to a constants.py

2024-05-06 04:36 UTC, farizrahman4u commented on datatune/storage/base.py
> +from abc import ABC, abstractmethod
All of these files are blindly copy pasted from the old repo.

2024-05-10 06:21 UTC, farizrahman4u requested changes

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/constants.py
> +HTTP_STATUS_FORCE_LIST = [408, 429, 500, 502, 503, 504]
New line end of file

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/dataset.py
> +    def __init__(self, api, name):
__init__(self, workspace, id)

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/view.py
> +        response = self.workspace.api.put(f"workspaces/{self.workspace.workspace_name}/views/{self.name}",
These apis should be wrapped in function in the api class.

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/view.py
> +    def is_pytorch_converted(self):
There are no pytorch related functionality on the server. It doesn't know that pytorch exists. We also don't have a pytorcb conversion step.

2024-05-10 06:21 UTC, farizrahman4u commented on examples/demo.py
> +queried_view = view.query(sql_query)
Instead of sql we should consider a pythonic api that builds the required sql query underneath.

2024-05-10 06:21 UTC, farizrahman4u commented on examples/demo.py
> +ts = dt.TorchStream(queried_view)
The api would be ts = queried_view.torch()

2024-05-10 06:21 UTC, farizrahman4u commented on examples/storage_example.py
> +from datatune import Storage
Delete this file

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/query.py
> +import pandas as pd
Should probably just delete this file. Doesn't make sense. A filtered/queried view can hold all the information in itself.

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/query.py
> +            except ValueError as e:
Why are we building pandas dataframes here??

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/storage.py
> +class Storage:
This needs to be re thought. We should be able to add external datasets (s3, hf urls) and we may support uploading data from local to storage (it's ok if we don't do that now). Also I don't see anything related to managed credentials.

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/stream.py
> +        endpoint = f"{self.view.workspace.api.base_url}/stream_pytorch/{self.view.name}"
We don't have any endpoints specific to pytorch.

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/stream.py
> +                for line in response.iter_lines():
We don't stream through the rest api, we stream directly from storage.

2024-05-10 06:21 UTC, farizrahman4u commented on datatune/stream.py
> +                        batch_data.append(processed_data)
Batching etc should be done by an optimized library.

2024-05-10 06:40 UTC, abhijithneilabraham commented on datatune/view.py
> +    def is_pytorch_converted(self):
Does this mean the view.extend(), view.filter(), all methods should be working under the assumption that the view is a TorchDataset all along?

2024-05-10 06:41 UTC, abhijithneilabraham commented on datatune/query.py
> +            except ValueError as e:
If I perform a query using SQL, the API returns a response, how should the response be wrapped so that I can use the queried_view.display() method to display the given data (hence I currently used dataframe, what are the other options?). Should the view be a TorchDataset after performing the query operations?

2024-05-27 00:10 UTC, farizrahman4u approved these changes

2024-05-27 00:10 UTC, merged